---
title: "210810_GGformation"
author: "박성군(tjdrns27@kribb.re.kr)"
date: '2021 8 10 '
output: html_document
---

``` {r}
library(showtext)
nanum_path = 'C:\\Users\\Lelp\\AppData\\Local\\Microsoft\\Windows\\Fonts\\NanumSquareEB.ttf'
font_paths(nanum_path)
font_add(family = 'NanumSquare', regular = nanum_path)

showtext_auto()
```

### Barcode01 = PR new Lib

#### Module Lib(barplot)
``` {r, eval=TRUE, message=FALSE}
library(tidyverse)

barcode01 = "C://workspace//work//colony_scan//barcode01_count.txt"


df <- read.table(barcode01, sep = "\t")
df$V1 <- apply(X=df,
      MARGIN=1,
      FUN=function(i) {
        sub(pattern="_sfGFP", replacement="", i["V1"])
      })
df$pro <- stringr::str_split_fixed(df$V1, "_", 3)[,1]
df$rbs <- stringr::str_split_fixed(df$V1, "_", 3)[,2]
```


#### Heatmap
``` {r, eval=TRUE}
pro <- data.frame(pro=c("P1", "P9", "P15", "P16"), count=c(1, 1, 1, 1))
rbs <- data.frame(rbs=c("R7", "R11", "R21", "R22", "R23"), count=c(1, 1, 1, 1, 1))

tmp <- apply(X=rbs,
      MARGIN=1,
      FUN=function(i){
        apply(X=pro,
              MARGIN=1,
              FUN=function(i2) {
                as.numeric(i["count"]) * as.numeric(i2["count"])
              })
      })
rownames(tmp) <- unlist(pro["pro"])
colnames(tmp) <- unlist(rbs["rbs"])
tmp2 <- tmp %>% data.frame() %>% pivot_longer(everything(), names_to="rbs")
tmp3 <- t(tmp) %>% data.frame() %>% pivot_longer(everything(), names_to="pro")
tmp4 <- merge(tmp2,tmp3)
tmp4$value <- tmp4$value/max(tmp4$value)
```

``` {r}
t1 <- tmp4 %>% ggplot(aes(x=pro, y=rbs, fill=value)) + geom_tile(color='white') +
  guides(fill = guide_colourbar(ticks=FALSE)) +
  theme_light() +
  scale_fill_distiller(palette="Blues", direction=-1,limits=c(0,1)) +
  theme(axis.title=element_blank(),
        axis.text=element_text(size=34, family="NanumSquare"),
        legend.position='none',
        legend.title = element_blank(),
        legend.text = element_text(size=10, family='NanumSquare')) +
  scale_y_discrete(limits=c("R7", 'R11', 'R21', 'R22', 'R23')) +
  scale_x_discrete(limits=c("P1", 'P9', 'P15', 'P16')) 

t1
ggsave("C://workspace//work//colony_scan//png//fig1//1_heat_arrange_part.png", t1, width=2.5, height=2)

t2 <- df %>% ggplot(aes(y=rbs, x=pro, fill=V2/max(V2))) + geom_tile(color='white') +
  guides(fill = guide_colourbar(ticks=FALSE)) +
  theme_light() +
  scale_fill_distiller(palette = "Blues", direction=-1, limits=c(0,1)) +
  theme(axis.title=element_blank(),
        axis.text=element_text(size=34, family="NanumSquare"),
        legend.position='none',
        legend.title = element_blank(),
        legend.text = element_text(size=10, family='NanumSquare')) +
  scale_y_discrete(limits=c("R7", 'R11', 'R21', 'R22', 'R23')) +
  scale_x_discrete(limits=c("P1", 'P9', 'P15', 'P16')) 

t2
ggsave("C://workspace//work//colony_scan//png//fig1//1_heat_arrange_seq.png", t2, width=2.5, height=2)
```

## Barplot
``` {r}
df$V1 %>% order()
part_order = c(20,16:19, 5, 1:4, 10, 6:9, 15, 11:14)
df$V1[part_order]

mycolor <- RColorBrewer::brewer.pal(6, 'Reds')
mycolor2 <- mycolor[2:5]

b1 <- df %>% ggplot(aes(x=V1, y=V2/max(V2), fill=pro)) +
  geom_bar(stat='identity') + theme_bw() +
  scale_fill_manual(values = mycolor2) +
  scale_x_discrete(limits = df$V1[part_order]) +
  theme(axis.title=element_blank(),
        legend.position = 'none',
        axis.text=element_text(size=34, family='NanumSquare'),
        axis.text.x=element_text(size=30, angle=45, hjust=1))


b1
ggsave("C://workspace//work//colony_scan//png//fig1//1_bar_arranged.png", b1, width=5, height=2)
```

### Barcode02 = PR old Lib

#### Module Lib(barplot)
``` {r, eval=TRUE, warning=FALSE} 

barcode02 = "C://workspace//work//colony_scan//barcode02_count.txt"


df2 <- read.table(barcode02, sep = "\t")
df2$V1 <- apply(X=df2,
      MARGIN=1,
      FUN=function(i) {
        sub(pattern="_sfGFP", replacement="", i["V1"])
      })
df2$pro <- stringr::str_split_fixed(df2$V1, "_", 3)[,1]
df2$rbs <- stringr::str_split_fixed(df2$V1, "_", 3)[,2]
```

#### Heatmap
``` {r, eval=TRUE}
pro <- data.frame(pro=c("P1", "P9", "P15", "P16"), count=c(2.24, 3.35, 1, 1.54))
rbs <- data.frame(rbs=c("R7", "R11", "R21", "R22", "R23"), count=c(1.75, 1, 2.94, 2.89, 1.90))

tmp <- apply(X=pro,
      MARGIN=1,
      FUN=function(i){
        apply(X=rbs,
              MARGIN=1,
              FUN=function(i2) {
                as.numeric(i["count"]) * as.numeric(i2["count"])
              })
      })
colnames(tmp) <- unlist(pro["pro"])
rownames(tmp) <- unlist(rbs["rbs"])
tmp2 <- tmp %>% data.frame() %>% pivot_longer(everything(), names_to="pro")
tmp3 <- t(tmp) %>% data.frame() %>% pivot_longer(everything(), names_to="rbs")
tmp4 <- merge(tmp2,tmp3)
tmp4$value <- tmp4$value/max(tmp4$value)
```


``` {r}
t1 <- tmp4 %>% ggplot(aes(x=pro, y=rbs, fill=value)) + geom_tile(color='white') +
  scale_fill_distiller(palette="Blues", direction=-1, limits=c(0,1)) +
  guides(fill = guide_colourbar(barwidth=10.5,
                                barheight=1)) + 
  theme_light() + theme(axis.title=element_blank(),
                        axis.text=element_text(size=34, family='NanumSquare'),
                        legend.position="none",
                        legend.title=element_blank()) +
  scale_y_discrete(limits=c("R7", 'R11', 'R21', 'R22', 'R23')) +
  scale_x_discrete(limits=c("P1", 'P9', 'P15', 'P16'))

t1
ggsave("C://workspace//work//colony_scan//png//fig1//1_heat_unarrange_part.png", t1, width=2.5, height=2)


t2 <- df2 %>% ggplot(aes(x=pro, y=rbs, fill=V2/max(V2))) + geom_tile(color='white') +
  scale_fill_distiller(palette="Blues", direction=-1, limits=c(0,1)) +
  theme_light() + theme(axis.title=element_blank(),
                        axis.text=element_text(size=34, family='NanumSquare'),
                        legend.position="none",
                        legend.title=element_blank()) +
  scale_y_discrete(limits=c("R7", 'R11', 'R21', 'R22', 'R23')) +
  scale_x_discrete(limits=c("P1", 'P9', 'P15', 'P16'))

t2
ggsave("C://workspace//work//colony_scan//png//fig1//1_heat_unarrange_seq.png", t2, width=2.5, height=2)
```

## Barplot
``` {r}
df2$V1 %>% order()
part_order = c(20,16:19, 5, 1:4, 10, 6:9, 15, 11:14)
df2$V1[part_order]


b1 <- df2 %>% ggplot(aes(x=V1, y=V2/max(V2), fill=pro)) +
  geom_bar(stat='identity') + theme_bw() +
  scale_fill_manual(values = mycolor2) +
  scale_x_discrete(limits = df$V1[part_order]) +
  theme(axis.title=element_blank(),
        legend.position = 'none',
        axis.text=element_text(size=34, family='NanumSquare'),
        axis.text.x=element_text(size=30, angle=45, hjust=1))


b1
ggsave("C://workspace//work//colony_scan//png//fig1//1_bar_unarranged.png", b1, width=5, height=2)
```